version: '1.0'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: promise-road-prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - promise-road-network

  grafana:
    image: grafana/grafana:latest
    container_name: promise-road-grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - promise-road-network

volumes:
  prometheus_data:
  grafana_data:

networks:
  promise-road-network:
    external: true
