version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: promise-road-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    networks:
      - promise-road-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: promise-road-backend
    restart: always
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://admin:password@mongodb:27017/promise_road?authSource=admin
      - JWT_SECRET=promise_road_secret_key_for_secure_authentication
      - JWT_EXPIRE=7d
      - NODE_ENV=production
      - UPLOAD_DIR=uploads
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - promise-road-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: promise-road-frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - promise-road-network

# Volumes
volumes:
  mongodb_data:
  uploads_data:

# Networks
networks:
  promise-road-network:
    driver: bridge
