version: '1.0'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.0
    container_name: promise-road-filebeat
    volumes:
      - ./logging/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    restart: always
    networks:
      - promise-road-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: promise-road-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always
    networks:
      - promise-road-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: promise-road-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    restart: always
    depends_on:
      - elasticsearch
    networks:
      - promise-road-network

volumes:
  elasticsearch_data:

networks:
  promise-road-network:
    external: true
