{
 "title": "Promise Road Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{job=\"backend\"}[1m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "API Response Time (95th percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds{job=\"backend\", quantile=\"0.95\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Node.js Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{job=\"backend\"}"
    }
   ]
  },
  {
   "title": "Total 5xx Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(http_request_total{job=\"backend\", status_code=~\"5..\"})"
    }
   ]
  }
 ]
}